export const SET_USER = "SET_USER";
export const SET_ORGS_AND_ADMINS = "SET_ORGS_AND_ADMINS"
export const SET_TASKS_AND_USERS = "SET_TASKS_AND_USERS"
export const SET_NODES_AND_LINKS = "SET_NODES_AND_LINKS"